FROM docker:19.03.12

RUN set -eux; 
RUN apk add --no-cache build-base python3 python3-dev py3-pip py3-setuptools py3-wheel libffi-dev openssl-dev;
RUN pip3 install pybuilder ddadevops deprecation python-terraform boto3 mfa