name: build
on:
  push:
    tags:
      - never

jobs:
  build:
    name: build&upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Use python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybuilder ddadevops deprecation setuptools

    - name: debug
      run: |
        echo ${{ github.ref }}
        echo ${{ github.ref == '[0-9]+.[0-9]+.[0-9]' }}
        echo ${{ github.ref != '[0-9]+.[0-9]+.[0-9]' }}
    
    - name: build stable release
      if: ${{ github.tag == '[0-9]+.[0-9]+.[0-9]' }}
      env:
        TWINE_USERNAME: dda
        TWINE_PASSWORD: ${{ secrets.PYPI_DDA }}
      run: |
        pyb -P version=${{ github.tag }} publish upload

    - name: build unstable release
      if: ${{ github.tag != '[0-9]+.[0-9]+.[0-9]' }}
      env:
        TWINE_USERNAME: dda
        TWINE_PASSWORD: ${{ secrets.PYPI_DDA }}
      run: |
        pyb publish upload

    - name: Create GH Release
      if: ${{ github.tag == '[0-9]+.[0-9]+.[0-9]' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
