name: stable
on: 
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: test-my build
    runs-on: ubuntu-latest

    steps:
    
    - name: debug
      run: |
        echo ${{ github.ref }}
        echo ${{ github.ref == '[0-9]+.[0-9]+.[0-9]+' }}
        echo ${{ github.ref != '[0-9]+.[0-9]+.[0-9]+' }}
