name: unstable
on: 
  push:
    tags:
      - '![0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: unstable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Use python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: build unstable release
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_DDA }}
      run: |
        pyb publish upload
